#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
###########################################################################
# Copyright © 1998 - 2026 Tencent. All Rights Reserved.
###########################################################################
"""
Monitor panel configuration builder for Gorge Chase.
峡谷追猎监控面板配置构建器。
"""


from kaiwudrl.common.monitor.monitor_config_builder import MonitorConfigBuilder


def build_monitor():
    """
    This function is used to create monitoring panel configurations for custom indicators.
    该函数用于创建自定义指标的监控面板配置。
    """
    monitor = MonitorConfigBuilder()

    config_dict = (
        monitor.title("峡谷追猎")
        
        # ==================== 算法指标 ====================
        .add_group(
            group_name="算法指标",
            group_name_en="algorithm",
        )
        .add_panel(
            name="累积回报",
            name_en="reward",
            type="line",
        )
        .add_metric(
            metrics_name="reward",
            expr="avg(reward{})",
        )
        .end_panel()
        .add_panel(
            name="总损失",
            name_en="total_loss",
            type="line",
        )
        .add_metric(
            metrics_name="total_loss",
            expr="avg(total_loss{})",
        )
        .end_panel()
        .add_panel(
            name="价值损失",
            name_en="value_loss",
            type="line",
        )
        .add_metric(
            metrics_name="value_loss",
            expr="avg(value_loss{})",
        )
        .end_panel()
        .add_panel(
            name="策略损失",
            name_en="policy_loss",
            type="line",
        )
        .add_metric(
            metrics_name="policy_loss",
            expr="avg(policy_loss{})",
        )
        .end_panel()
        .add_panel(
            name="熵损失",
            name_en="entropy_loss",
            type="line",
        )
        .add_metric(
            metrics_name="entropy_loss",
            expr="avg(entropy_loss{})",
        )
        .end_panel()
        .add_panel(
            name="Clip比例",
            name_en="clip_frac",
            type="line",
        )
        .add_metric(
            metrics_name="clip_frac",
            expr="avg(clip_frac{})",
        )
        .end_panel()
        .add_panel(
            name="解释方差",
            name_en="explained_var",
            type="line",
        )
        .add_metric(
            metrics_name="explained_var",
            expr="avg(explained_var{})",
        )
        .end_panel()
        .add_panel(
            name="Advantage均值",
            name_en="adv_mean",
            type="line",
        )
        .add_metric(
            metrics_name="adv_mean",
            expr="avg(adv_mean{})",
        )
        .end_panel()
        .add_panel(
            name="Return均值",
            name_en="ret_mean",
            type="line",
        )
        .add_metric(
            metrics_name="ret_mean",
            expr="avg(ret_mean{})",
        )
        .end_panel()
        
        # ==================== 训练指标 ====================
        .add_group(
            group_name="训练指标",
            group_name_en="train",
        )
        .add_panel(
            name="总奖励",
            name_en="train_reward",
            type="line",
        )
        .add_metric(
            metrics_name="reward",
            expr="avg(reward{})",
        )
        .end_panel()
        .add_panel(
            name="总分",
            name_en="total_score",
            type="line",
        )
        .add_metric(
            metrics_name="total_score",
            expr="avg(total_score{})",
        )
        .end_panel()
        .add_panel(
            name="宝箱数量",
            name_en="treasures",
            type="line",
        )
        .add_metric(
            metrics_name="treasures",
            expr="avg(treasures{})",
        )
        .end_panel()
        .add_panel(
            name="总步数",
            name_en="steps",
            type="line",
        )
        .add_metric(
            metrics_name="steps",
            expr="avg(steps{})",
        )
        .end_panel()
        .add_panel(
            name="加速前步数",
            name_en="pre_steps",
            type="line",
        )
        .add_metric(
            metrics_name="pre_steps",
            expr="avg(pre_steps{})",
        )
        .end_panel()
        .add_panel(
            name="加速后步数",
            name_en="post_steps",
            type="line",
        )
        .add_metric(
            metrics_name="post_steps",
            expr="avg(post_steps{})",
        )
        .end_panel()
        .add_panel(
            name="加速前Shaping奖励",
            name_en="pre_shaped_reward",
            type="line",
        )
        .add_metric(
            metrics_name="pre_shaped_reward",
            expr="avg(pre_shaped_reward{})",
        )
        .end_panel()
        .add_panel(
            name="加速后Shaping奖励",
            name_en="post_shaped_reward",
            type="line",
        )
        .add_metric(
            metrics_name="post_shaped_reward",
            expr="avg(post_shaped_reward{})",
        )
        .end_panel()
        .add_panel(
            name="加速前宝箱得分",
            name_en="pre_treasure_gain",
            type="line",
        )
        .add_metric(
            metrics_name="pre_treasure_gain",
            expr="avg(pre_treasure_gain{})",
        )
        .end_panel()
        .add_panel(
            name="加速后宝箱得分",
            name_en="post_treasure_gain",
            type="line",
        )
        .add_metric(
            metrics_name="post_treasure_gain",
            expr="avg(post_treasure_gain{})",
        )
        .end_panel()
        .add_panel(
            name="加速前终局奖励",
            name_en="pre_terminal",
            type="line",
        )
        .add_metric(
            metrics_name="pre_terminal",
            expr="avg(pre_terminal{})",
        )
        .end_panel()
        .add_panel(
            name="加速后终局奖励",
            name_en="post_terminal",
            type="line",
        )
        .add_metric(
            metrics_name="post_terminal",
            expr="avg(post_terminal{})",
        )
        .end_panel()
        .add_panel(
            name="闪现次数",
            name_en="flash_count",
            type="line",
        )
        .add_metric(
            metrics_name="flash_count",
            expr="avg(flash_count{})",
        )
        .end_panel()
        .add_panel(
            name="最后一步闪现使用",
            name_en="last_flash_used",
            type="line",
        )
        .add_metric(
            metrics_name="last_flash_used",
            expr="avg(last_flash_used{})",
        )
        .end_panel()
        .add_panel(
            name="最后一步闪现可用",
            name_en="last_flash_ready",
            type="line",
        )
        .add_metric(
            metrics_name="last_flash_ready",
            expr="avg(last_flash_ready{})",
        )
        .end_panel()
        .add_panel(
            name="最后一步闪现合法",
            name_en="last_flash_legal",
            type="line",
        )
        .add_metric(
            metrics_name="last_flash_legal",
            expr="avg(last_flash_legal{})",
        )
        .end_panel()
        .add_panel(
            name="最终危险度",
            name_en="final_danger",
            type="line",
        )
        .add_metric(
            metrics_name="final_danger",
            expr="avg(final_danger{})",
        )
        .end_panel()
        .add_panel(
            name="最终宝箱距离",
            name_en="final_treasure_dist",
            type="line",
        )
        .add_metric(
            metrics_name="final_treasure_dist",
            expr="avg(final_treasure_dist{})",
        )
        .end_panel()
        .add_panel(
            name="视野内宝箱比例",
            name_en="final_visible_treasure",
            type="line",
        )
        .add_metric(
            metrics_name="final_visible_treasure",
            expr="avg(final_visible_treasure{})",
        )
        .end_panel()
        .add_panel(
            name="是否进入加速阶段",
            name_en="speedup_reached",
            type="line",
        )
        .add_metric(
            metrics_name="speedup_reached",
            expr="avg(speedup_reached{})",
        )
        .end_panel()
        
        # ==================== 验证指标 ====================
        .add_group(
            group_name="验证指标",
            group_name_en="validation",
        )
        .add_panel(
            name="验证奖励",
            name_en="val_reward",
            type="line",
        )
        .add_metric(
            metrics_name="val_reward",
            expr="avg(val_reward{})",
        )
        .end_panel()
        .add_panel(
            name="验证总分",
            name_en="val_total_score",
            type="line",
        )
        .add_metric(
            metrics_name="val_total_score",
            expr="avg(val_total_score{})",
        )
        .end_panel()
        .add_panel(
            name="验证步数",
            name_en="val_steps",
            type="line",
        )
        .add_metric(
            metrics_name="val_steps",
            expr="avg(val_steps{})",
        )
        .end_panel()
        
        # ==================== 统计指标 ====================
        .add_group(
            group_name="统计指标",
            group_name_en="statistics",
        )
        .add_panel(
            name="阵亡率",
            name_en="terminated_rate",
            type="line",
        )
        .add_metric(
            metrics_name="terminated_rate",
            expr="avg(terminated_rate{})",
        )
        .end_panel()
        .add_panel(
            name="完成率",
            name_en="completed_rate",
            type="line",
        )
        .add_metric(
            metrics_name="completed_rate",
            expr="avg(completed_rate{})",
        )
        .end_panel()
        .end_group()
        .build()
    )
    return config_dict
